# Permalinks
permalink:           pretty

# Setup
title:               Jorge Cimentada
tagline:             cimentadaj
url:                 http://www.jorgecimentada.com
paginate:            5
paginate_path:       "/blog/page:num/"
baseurl:             ""
encoding:            utf-8

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jorge Cimentada
  url:               https://www.jorgecimentada.com
  email:             cimentadaj@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cimentadaj/cimentadaj.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:       
  Blog: '/blog'
  Learning and resources: '/Learning and resources'
  CV: '/CV'
