# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Jorge Cimentada
tagline:             'PhD Candidate and R enthusiast'
description:         'Something'
url:                 http://cimentadaj.github.io
baseurl:             ''
paginate:            5

# About/contact
author:              
  name:              Jorge Cimentada
  url:               www.jorgecimentada.com
  email:             http://cimentadaj.github.io

# Custom vars
version:             1.0.0
gems:                [jekyll-paginate]
